"""Artifact catalogue for P006.7.11.12."""
from ._shared import ROAD_POLICY,ROAD_GEOMETRIES,ROAD_SEGMENTS,NETWORK_NODES,CONNECTIVITY,ROAD_RELATIONSHIPS,ASSIGNMENTS,QUALIFICATION,SOURCE_HASHES,SUMMARY
ARTIFACTS=(ROAD_POLICY,ROAD_GEOMETRIES,ROAD_SEGMENTS,NETWORK_NODES,CONNECTIVITY,ROAD_RELATIONSHIPS,ASSIGNMENTS,QUALIFICATION,SOURCE_HASHES,SUMMARY)
def missing_artifacts(): return tuple(p for p in ARTIFACTS if not p.exists() or p.stat().st_size==0)
