from ._shared import POLICY,CANDIDATES,DECISIONS,PROJECTION_CANDIDATES,QUALIFICATION,SOURCE_HASHES,SUMMARY
ARTIFACTS=(POLICY,CANDIDATES,DECISIONS,PROJECTION_CANDIDATES,QUALIFICATION,SOURCE_HASHES,SUMMARY)
def missing_artifacts():return tuple(p for p in ARTIFACTS if not p.exists() or p.stat().st_size==0)
