from typing import Protocol,Iterable
from infrastructure.database.models import GovernedDatasetRecord
class DatasetRepository(Protocol):
    def save(self,record:GovernedDatasetRecord)->None: ...
    def get(self,dataset_id:str,version:int|None=None)->GovernedDatasetRecord|None: ...
    def list(self)->Iterable[GovernedDatasetRecord]: ...
