from ._shared import HYDRO_RELATIONSHIPS,LANDFORM_EXTENTS,GEOGRAPHIC_NAMES,NAME_ASSIGNMENTS,QUALIFICATION,SOURCE_HASHES,SUMMARY
ARTIFACTS=(HYDRO_RELATIONSHIPS,LANDFORM_EXTENTS,GEOGRAPHIC_NAMES,NAME_ASSIGNMENTS,QUALIFICATION,SOURCE_HASHES,SUMMARY)
def missing_artifacts(): return tuple(p for p in ARTIFACTS if not p.exists() or p.stat().st_size==0)
