from abc import ABC,abstractmethod
class ManualNameCandidateRepository(ABC):
 @abstractmethod
 def add(self,candidate):...
 @abstractmethod
 def get(self,candidate_id):...
 @abstractmethod
 def replace(self,candidate):...
class NameAuthorityRepository(ABC):
 @abstractmethod
 def create_or_get(self,record):...
 @abstractmethod
 def get(self,authority_name_id):...
 @abstractmethod
 def find_equivalent(self,runtime_mode,composition_key):...
