from __future__ import annotations

"""Issuance-specific registry exceptions."""

from .registry_error import (
    RegistryConflictError,
    RegistryIntegrityError,
    RegistryNotFoundError,
    RegistryOperationError,
    RegistryStateError,
    RegistryValidationError,
)


class IssuanceError(RegistryOperationError): ...
class IssuanceValidationError(RegistryValidationError, IssuanceError): ...
class IssuanceNotFoundError(RegistryNotFoundError, IssuanceError): ...
class IssuanceConflictError(RegistryConflictError, IssuanceError): ...
class IdentifierAlreadyIssuedError(IssuanceConflictError): ...
class DuplicateIssuanceRequestError(IssuanceConflictError): ...
class IssuanceStateError(RegistryStateError, IssuanceError): ...
class IssuancePendingError(IssuanceStateError): ...
class IssuanceCompletedError(IssuanceStateError): ...
class IssuanceCancelledError(IssuanceStateError): ...
class IssuanceExpiredError(IssuanceStateError): ...
class IssuanceIntegrityError(RegistryIntegrityError, IssuanceError): ...
class IssuanceSequenceError(IssuanceIntegrityError): ...
class IssuanceLifecycleError(IssuanceIntegrityError): ...
class IssuanceDefinitionMismatchError(IssuanceIntegrityError): ...

__all__ = (
    "IssuanceError",
    "IssuanceValidationError",
    "IssuanceNotFoundError",
    "IssuanceConflictError",
    "IdentifierAlreadyIssuedError",
    "DuplicateIssuanceRequestError",
    "IssuanceStateError",
    "IssuancePendingError",
    "IssuanceCompletedError",
    "IssuanceCancelledError",
    "IssuanceExpiredError",
    "IssuanceIntegrityError",
    "IssuanceSequenceError",
    "IssuanceLifecycleError",
    "IssuanceDefinitionMismatchError",
)
