from __future__ import annotations

"""Ownership-specific registry exceptions."""

from .registry_error import (
    RegistryConflictError,
    RegistryIntegrityError,
    RegistryNotFoundError,
    RegistryOperationError,
    RegistryStateError,
    RegistryValidationError,
)

class OwnershipError(RegistryOperationError): ...
class OwnershipValidationError(RegistryValidationError, OwnershipError): ...
class OwnershipNotFoundError(RegistryNotFoundError, OwnershipError): ...
class OwnershipConflictError(RegistryConflictError, OwnershipError): ...
class OwnershipAlreadyExistsError(OwnershipConflictError): ...
class OwnershipTransferConflictError(OwnershipConflictError): ...
class OwnershipStateError(RegistryStateError, OwnershipError): ...
class OwnershipInactiveError(OwnershipStateError): ...
class OwnershipSuspendedError(OwnershipStateError): ...
class OwnershipRevokedError(OwnershipStateError): ...
class OwnershipImmutableError(OwnershipStateError): ...
class OwnershipIntegrityError(RegistryIntegrityError, OwnershipError): ...
class OwnershipHolderMismatchError(OwnershipIntegrityError): ...
class OwnershipResourceMismatchError(OwnershipIntegrityError): ...
class OwnershipPeriodOverlapError(OwnershipIntegrityError): ...

__all__ = (
    "OwnershipError",
    "OwnershipValidationError",
    "OwnershipNotFoundError",
    "OwnershipConflictError",
    "OwnershipAlreadyExistsError",
    "OwnershipTransferConflictError",
    "OwnershipStateError",
    "OwnershipInactiveError",
    "OwnershipSuspendedError",
    "OwnershipRevokedError",
    "OwnershipImmutableError",
    "OwnershipIntegrityError",
    "OwnershipHolderMismatchError",
    "OwnershipResourceMismatchError",
    "OwnershipPeriodOverlapError",
)
