/** P006.UI.2 — Simulation entry placeholder; no simulated behaviour is invented here. */
export function simulationEntryMarkup() {
  return `
    <section class="entry-page" aria-labelledby="simulation-entry-title">
      <p class="eyebrow">Simulation</p>
      <h1 id="simulation-entry-title">NexiLabs Simulation</h1>
      <p class="summary">The Simulation Workspace will be introduced in Bundle 12E. No simulation activity is generated by this entry page.</p>
      <div class="planned-panel" role="note">
        <strong>Available now</strong>
        <span>Runtime context and application navigation.</span>
      </div>
      <button class="text-button" type="button" data-action="back">← Back</button>
    </section>`;
}
