"""Storage-neutral repository contract for canonical name records."""
from __future__ import annotations
from abc import ABC, abstractmethod
from .canonical_name import CanonicalName
from .name_search_query import NameSearchQuery
from .name_search_result import NameSearchResult
class NameRepository(ABC):
    @abstractmethod
    def add(self,record:CanonicalName)->CanonicalName: ...
    @abstractmethod
    def get(self,name_id:str)->CanonicalName: ...
    @abstractmethod
    def replace(self,record:CanonicalName)->CanonicalName: ...
    @abstractmethod
    def exists(self,name_id:str)->bool: ...
    @abstractmethod
    def count(self)->int: ...
    @abstractmethod
    def list_all(self)->tuple[CanonicalName,...]: ...
    @abstractmethod
    def search(self,query:NameSearchQuery)->NameSearchResult: ...
__all__=["NameRepository"]
