"""Authoritative Bundle 19B artifact inventory."""
from ._shared import TOPOLOGY_POLICY,BOUNDARIES,TOPOLOGY_RELATIONSHIPS,ASSIGNMENTS,LEGALIZATION_DECISIONS,QUALIFICATION_RESULTS,SOURCE_HASHES,SUMMARY
ARTIFACT_PATHS=(TOPOLOGY_POLICY,BOUNDARIES,TOPOLOGY_RELATIONSHIPS,ASSIGNMENTS,LEGALIZATION_DECISIONS,QUALIFICATION_RESULTS,SOURCE_HASHES,SUMMARY)
def missing_artifacts(): return tuple(p for p in ARTIFACT_PATHS if not p.exists() or p.stat().st_size==0)
