/** P003.3/P003.4 — Immutable application-shell cache policy. */
export const PWA_CACHE_VERSION = "novegeo-shell-v7";
export const OFFLINE_DOCUMENT = "./index.html";
export const APPLICATION_SHELL_ASSETS = Object.freeze([
  "./",
  "./index.html",
  "./public/manifest.webmanifest",
  "./public/brand/nexilabs/metadata/brand-tokens.css",
  "./public/brand/nexilabs/vectors/nexilabs_logo_horizontal.svg",
  "./public/brand/nexilabs/pwa/nexilabs_icon_192x192.png",
  "./public/brand/nexilabs/pwa/nexilabs_icon_512x512.png",
  "./styles/app.css",
  "./src/main.js",
  "./src/app/application.js",
  "./src/branding/brand-assets.js",
  "./src/branding/brand-config.js",
  "./src/config/runtime-config.js",
  "./src/core/application-state.js",
  "./src/pwa/cache-policy.js",
  "./src/pwa/service-worker-registration.js",
  "./src/map/geography/contracts.js",
  "./src/map/geography/projection.js",
  "./src/map/geography/status.js",
  "./src/map/presentation/boundary-render-plan.js",
  "./src/map/presentation/canvas-renderer.js",
  "./src/map/presentation/contracts.js",
  "./src/map/presentation/coordinate-grid.js",
  "./src/map/presentation/coordinate-labels.js",
  "./src/map/presentation/index.js",
  "./src/map/presentation/map-presentation.js",
  "./src/map/presentation/publication.js",
  "./src/map/presentation/viewport.js",
  "./src/map/publication/contracts.js",
  "./src/map/publication/catalog.js",
  "./src/map/publication/index.js",
  "./src/map/publication/v002-overview.js",
  "./src/map/publication/v002-standard.js",
  "./public/geography/novegeo/world-boundary/v002/manifest.json",
  "./public/geography/novegeo/world-boundary/v002/overview.geojson",
  "./public/geography/novegeo/world-boundary/v002/standard.geojson",
  "./src/map/validation/contracts.js",
  "./src/map/validation/geometry-validator.js",
  "./src/map/validation/extent-calculator.js",
  "./src/map/validation/extent-validator.js",
  "./src/map/validation/projection-validator.js",
  "./src/map/validation/viewport-validator.js",
  "./src/map/validation/qualification.js",
  "./src/map/validation/index.js",
  "./src/map/terrain/contracts.js",
  "./src/map/terrain/catalog.js",
  "./src/map/terrain/render-plan.js",
  "./src/map/landforms/contracts.js",
  "./src/map/landforms/catalog.js",
  "./src/map/landforms/render-plan.js",
  "./src/map/environment/physical-land-presentation.js",
  "./src/map/environment/full-viewport-coordinate-presentation.js",
  "./src/map/lifecycle/foreground-recovery.js",
  "./src/map/hydrology/contracts.js",
  "./src/map/hydrology/catalog.js",
  "./src/map/hydrology/render-plan.js",
  "./src/map/climate/contracts.js",
  "./src/map/climate/catalog.js",
  "./src/map/climate/render-plan.js",
  "./src/map/environment/hydrology-atmosphere-presentation.js",
  "./public/geography/novegeo/hydrology/v001/manifest.json",
  "./public/geography/novegeo/hydrology/v001/standard.json",
  "./public/geography/novegeo/climate/v001/manifest.json",
  "./public/geography/novegeo/climate/v001/standard.json",
  "./public/geography/novegeo/terrain/v001/manifest.json",
  "./public/geography/novegeo/terrain/v001/overview.json",
  "./public/geography/novegeo/terrain/v001/standard.json",
  "./public/geography/novegeo/landforms/v001/manifest.json",
  "./public/geography/novegeo/landforms/v001/standard.geojson"
]);

export function isCurrentApplicationCache(cacheName) {
  return cacheName === PWA_CACHE_VERSION;
}
